#!/bin/sh

repo_root="$(git rev-parse --show-toplevel)" || exit 1
pwsh -NoProfile -File "$repo_root/scripts/git/pre-push.ps1" -RepositoryRoot "$repo_root" || exit $?

command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
exec git lfs pre-push "$@"
