using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using static Lakona.Game.Server.Hotfix.Generators.GeneratorSymbolFacts;

namespace Lakona.Game.Server.Hotfix.Generators
{
    internal static class HotfixRpcServiceGenerator
    {
        private const string RpcServiceAttributeName = "Lakona.Rpc.Core.RpcServiceAttribute";
        private const string RpcMethodAttributeName = "Lakona.Rpc.Core.RpcMethodAttribute";
        private const string RpcNotificationAttributeName = "Lakona.Rpc.Core.RpcNotificationAttribute";

        internal static void Register(
            IncrementalGeneratorInitializationContext context,
            IncrementalValueProvider<HotfixGeneratorOptions> options)
        {
            var services = context.CompilationProvider.Combine(options)
                .Select(static (input, cancellationToken) =>
                {
                    var (compilation, generatorOptions) = input;
                    if (!generatorOptions.GenerateStableRpcServices)
                    {
                        return [];
                    }

                    return DiscoverRpcServiceContracts(compilation, cancellationToken)
                        .Select(contract => new HotfixRpcServiceInfo(
                            contract,
                            generatorOptions.GeneratedServerNamespace,
                            generatorOptions.GeneratedServerNamespace))
                        .ToArray();
                });

            context.RegisterSourceOutput(services, GenerateRpcServices);

            var clientNotifications = context.CompilationProvider.Combine(options)
                .Select(static (input, cancellationToken) =>
                {
                    var (compilation, generatorOptions) = input;
                    if (compilation.GetTypeByMetadataName("Lakona.Game.Server.Sessions.ClientNotificationTarget`1") is null ||
                        compilation.GetTypeByMetadataName("Lakona.Game.Server.Sessions.GeneratedClientNotificationExtensions") is not null)
                    {
                        return [];
                    }

                    return DiscoverRpcServiceContracts(compilation, cancellationToken)
                        .Select(contract => new HotfixRpcServiceInfo(
                            contract,
                            generatorOptions.GeneratedServerNamespace,
                            generatorOptions.GeneratedServerNamespace))
                        .Where(static service => GetNotificationContract(service.Contract) is not null)
                        .ToArray();
                });

            context.RegisterSourceOutput(clientNotifications, GenerateClientNotificationExtensions);
        }

        private static void GenerateRpcServices(SourceProductionContext context, HotfixRpcServiceInfo[] services)
        {
            var supported = new List<HotfixRpcServiceInfo>();
            foreach (var service in services)
            {
                if (!ValidateRpcService(context, service))
                {
                    continue;
                }

                supported.Add(service);
                context.AddSource(
                    CreateRpcServiceHintName(service.Contract),
                    SourceText.From(GenerateRpcServiceSource(service), Encoding.UTF8));
            }

            if (supported.Count == 0)
            {
                return;
            }

            context.AddSource(
                "GeneratedHotfixServices.g.cs",
                SourceText.From(GenerateRpcServiceExtensionSource(supported.ToArray()), Encoding.UTF8));
        }

        private static void GenerateClientNotificationExtensions(
            SourceProductionContext context,
            HotfixRpcServiceInfo[] services)
        {
            if (services.Length == 0)
            {
                return;
            }

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("namespace Lakona.Game.Server.Sessions;");
            builder.AppendLine();
            builder.AppendLine("public static class GeneratedClientNotificationExtensions");
            builder.AppendLine("{");

            foreach (var service in services.OrderBy(
                static item => item.Contract.ToDisplayString(),
                System.StringComparer.Ordinal))
            {
                var serviceAttribute = service.Contract.GetAttributes()
                    .FirstOrDefault(static attribute =>
                        attribute.AttributeClass?.ToDisplayString() == RpcServiceAttributeName);
                var callback = GetNotificationContract(service.Contract);
                if (serviceAttribute?.ConstructorArguments.Length != 1 ||
                    serviceAttribute.ConstructorArguments[0].Value is not int serviceId ||
                    callback is null)
                {
                    continue;
                }

                var callbackDisplay = callback.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                foreach (var method in callback.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(static method => method.MethodKind == MethodKind.Ordinary)
                    .OrderBy(static method => method.Name, System.StringComparer.Ordinal))
                {
                    var notificationAttribute = method.GetAttributes()
                        .FirstOrDefault(static attribute =>
                            attribute.AttributeClass?.ToDisplayString() == RpcNotificationAttributeName);
                    if (notificationAttribute?.ConstructorArguments.Length != 1 ||
                        notificationAttribute.ConstructorArguments[0].Value is not int methodId ||
                        method.Parameters.Length is < 1 or > 2)
                    {
                        continue;
                    }

                    var payload = method.Parameters[0];
                    builder.AppendLine();
                    builder.Append("    public static global::Lakona.Game.Server.Sessions.ClientNotificationStatus ")
                        .Append(method.Name)
                        .Append("(this global::Lakona.Game.Server.Sessions.ClientNotificationTarget<")
                        .Append(callbackDisplay)
                        .Append("> target, ")
                        .Append(payload.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                        .Append(' ')
                        .Append(payload.Name)
                        .AppendLine(")");
                    builder.AppendLine("    {");
                    builder.Append("        return target.EnqueueGenerated(")
                        .Append(serviceId)
                        .Append(", ")
                        .Append(methodId)
                        .Append(", \"")
                        .Append(method.Name)
                        .Append("\", ")
                        .Append(payload.Name)
                        .AppendLine(");");
                    builder.AppendLine("    }");
                }
            }

            builder.AppendLine("}");
            context.AddSource(
                "GeneratedClientNotificationExtensions.g.cs",
                SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private static INamedTypeSymbol? GetNotificationContract(INamedTypeSymbol serviceContract)
        {
            var serviceAttribute = serviceContract.GetAttributes()
                .FirstOrDefault(static attribute =>
                    attribute.AttributeClass?.ToDisplayString() == RpcServiceAttributeName);
            return GetNamedTypeArgument(serviceAttribute, "NotificationContract");
        }

        private static string GenerateRpcServiceExtensionSource(HotfixRpcServiceInfo[] services)
        {
            var firstService = services[0];
            var namespaceName = firstService.GeneratedServerNamespace;
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();

            foreach (var service in services.OrderBy(static service =>
                service.Contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            {
                AppendEndpointRpcServiceBinder(builder, service);
            }

            builder.AppendLine("internal sealed class GeneratedHotfixRequiredServiceContracts :");
            builder.AppendLine("    global::Lakona.Game.Server.Hotfix.Abstractions.IHotfixRequiredServiceContracts");
            builder.AppendLine("{");
            builder.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::System.Type> ServiceContracts { get; } =");
            builder.AppendLine("    [");
            foreach (var service in services.OrderBy(static service =>
                service.Contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            {
                builder.Append("        typeof(")
                    .Append(service.Contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .AppendLine("),");
            }

            builder.AppendLine("    ];");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendEndpointRpcServiceBinder(StringBuilder builder, HotfixRpcServiceInfo service)
        {
            var serviceName = GetEndpointServiceName(service);
            var binderTypeName = GetServiceTypeName(service.Contract.Name) + "EndpointBinder";

            builder.Append("[global::Lakona.Game.Server.Hosting.LakonaRpcServiceAttribute(\"")
                .Append(EscapeStringLiteral(serviceName))
                .AppendLine("\")]");
            builder.Append("internal sealed class ").Append(binderTypeName)
                .AppendLine(" : global::Lakona.Game.Server.Hosting.LakonaRpcServiceBinder");
            builder.AppendLine("{");
            builder.AppendLine("    public override void Bind(global::Lakona.Game.Server.Hosting.LakonaGameServerRpcContext context)");
            builder.AppendLine("    {");
            builder.AppendLine("        var registry = context.Builder.ServiceRegistry;");
            builder.AppendLine("        var services = context.Services;");
            AppendRpcServiceBinding(builder, service);
            builder.AppendLine("    }");
            var rpcServiceAttribute = service.Contract.GetAttributes()
                .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == RpcServiceAttributeName);
            var callbackType = GetNamedTypeArgument(rpcServiceAttribute, "NotificationContract");
            if (callbackType != null)
            {
                var callbackDisplay = callbackType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var callbackProxyName =
                    service.GeneratedProxyNamespace + "." + GetNotificationProxyTypeName(callbackType.Name);
                builder.AppendLine();
                builder.AppendLine("    public override bool TryCreateCallback(");
                builder.AppendLine("        global::System.Type callbackContractType,");
                builder.AppendLine("        global::Lakona.Rpc.Server.RpcNotificationChannel notifications,");
                builder.AppendLine("        out object? callback)");
                builder.AppendLine("    {");
                builder.Append("        if (callbackContractType == typeof(").Append(callbackDisplay).AppendLine("))");
                builder.AppendLine("        {");
                builder.Append("            callback = new global::").Append(callbackProxyName).AppendLine("(notifications);");
                builder.AppendLine("            return true;");
                builder.AppendLine("        }");
                builder.AppendLine("        callback = null;");
                builder.AppendLine("        return false;");
                builder.AppendLine("    }");
            }

            builder.AppendLine("}");
            builder.AppendLine();
        }

        private static void AppendRpcServiceBinding(StringBuilder builder, HotfixRpcServiceInfo service)
        {
            var generatedNamespace = service.GeneratedProxyNamespace;
            var proxyType = GetGeneratedProxyTypeDisplay(service);
            var binderName = generatedNamespace + "." + GetBinderTypeName(service.Contract.Name);

            builder.Append("        global::").Append(binderName).AppendLine(".BindFactory(");
            builder.AppendLine("            registry,");
            builder.AppendLine("            connection => new " + proxyType + "(");
            builder.AppendLine("                global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Lakona.Game.Server.Hotfix.IHotfixRuntimeAccessor>(services),");
            builder.AppendLine("                global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Lakona.Game.Server.Actors.IActorRuntime>(services),");
            builder.AppendLine("                global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Lakona.Game.Server.ILakonaGameServer>(services),");
            builder.AppendLine("                connection.ConnectionId));");
            builder.AppendLine();
        }

        private static bool ValidateRpcService(SourceProductionContext context, HotfixRpcServiceInfo service)
        {
            if (!IsSupportedRpcServiceContract(service))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    HotfixGeneratorDiagnostics.UnsupportedServiceContract,
                    service.Contract.Locations.FirstOrDefault(),
                    service.Contract.ToDisplayString()));
                return false;
            }

            var rpcServiceAttribute = service.Contract.GetAttributes()
                .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == RpcServiceAttributeName);
            var callbackType = GetNamedTypeArgument(rpcServiceAttribute, "NotificationContract");
            if (callbackType != null && callbackType.TypeKind != TypeKind.Interface)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    HotfixGeneratorDiagnostics.UnsupportedNotificationContract,
                    service.Contract.Locations.FirstOrDefault(),
                    service.Contract.ToDisplayString()));
                return false;
            }

            foreach (var method in GetContractMethods(service.Contract))
            {
                var methodDisplay = method.ToDisplayString();
                var rpcMethod = method.GetAttributes()
                    .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == RpcMethodAttributeName);
                if (rpcMethod == null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        HotfixGeneratorDiagnostics.RpcMethodAttributeRequired,
                        method.Locations.FirstOrDefault() ?? service.Contract.Locations.FirstOrDefault(),
                        methodDisplay));
                    return false;
                }

                if (method.Parameters.Length != 1)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        HotfixGeneratorDiagnostics.RpcMethodRequiresSingleRequest,
                        method.Locations.FirstOrDefault() ?? service.Contract.Locations.FirstOrDefault(),
                        methodDisplay));
                    return false;
                }

                if (!IsSupportedRpcReturnType(method.ReturnType))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        HotfixGeneratorDiagnostics.UnsupportedRpcMethodReturnType,
                        method.Locations.FirstOrDefault() ?? service.Contract.Locations.FirstOrDefault(),
                        methodDisplay));
                    return false;
                }
            }

            return true;
        }

        private static bool IsSupportedRpcService(HotfixRpcServiceInfo service)
        {
            if (!IsSupportedRpcServiceContract(service))
            {
                return false;
            }

            var rpcServiceAttribute = service.Contract.GetAttributes()
                .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == RpcServiceAttributeName);
            var callbackType = GetNamedTypeArgument(rpcServiceAttribute, "NotificationContract");
            if (callbackType != null && callbackType.TypeKind != TypeKind.Interface)
            {
                return false;
            }

            return GetContractMethods(service.Contract)
                .All(method =>
                    method.GetAttributes().Any(attribute =>
                        attribute.AttributeClass?.ToDisplayString() == RpcMethodAttributeName) &&
                    method.Parameters.Length == 1 &&
                    IsSupportedRpcReturnType(method.ReturnType));
        }

        private static bool IsSupportedRpcServiceContract(HotfixRpcServiceInfo service)
        {
            return service.Contract.TypeKind == TypeKind.Interface &&
                service.Contract.GetAttributes()
                    .Any(attribute => attribute.AttributeClass?.ToDisplayString() == RpcServiceAttributeName);
        }

        private static IEnumerable<IMethodSymbol> GetContractMethods(INamedTypeSymbol contractType)
        {
            return contractType.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(method => method.MethodKind == MethodKind.Ordinary);
        }

        private static IEnumerable<INamedTypeSymbol> DiscoverRpcServiceContracts(
            Compilation compilation,
            CancellationToken cancellationToken)
        {
            if (compilation.GetTypeByMetadataName("Lakona.Game.Server.Hosting.LakonaGameServerBuilder") is null)
            {
                yield break;
            }

            var seen = new HashSet<string>();
            foreach (var contract in EnumerateTypes(compilation.Assembly.GlobalNamespace))
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (IsUserRpcService(contract) &&
                    seen.Add(contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
                {
                    yield return contract;
                }
            }

            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
            {
                cancellationToken.ThrowIfCancellationRequested();
                foreach (var contract in EnumerateTypes(assembly.GlobalNamespace))
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    if (IsUserRpcService(contract) &&
                        seen.Add(contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
                    {
                        yield return contract;
                    }
                }
            }
        }

        private static bool IsUserRpcService(INamedTypeSymbol contract)
        {
            var assemblyName = contract.ContainingAssembly?.Name ?? string.Empty;
            return !assemblyName.StartsWith("Lakona.", System.StringComparison.Ordinal) &&
                HasRpcServiceAttribute(contract);
        }

        private static bool HasRpcServiceAttribute(INamedTypeSymbol contract)
        {
            return contract.GetAttributes().Any(static attribute =>
                attribute.AttributeClass?.ToDisplayString() == RpcServiceAttributeName);
        }

        private static bool IsSupportedRpcReturnType(ITypeSymbol returnType)
        {
            return returnType is INamedTypeSymbol namedReturn &&
                namedReturn.ContainingNamespace.ToDisplayString() == "System.Threading.Tasks" &&
                namedReturn.Name == "ValueTask" &&
                (!namedReturn.IsGenericType || namedReturn.TypeArguments.Length == 1);
        }

        private static string GenerateRpcServiceSource(HotfixRpcServiceInfo service)
        {
            var namespaceName = service.GeneratedProxyNamespace;
            var contractDisplay = service.Contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var serviceTypeName = GetServiceTypeName(service.Contract.Name);
            var proxyName = serviceTypeName + "Proxy";
            var callTypeName = serviceTypeName + "Call";
            var callTypeDisplay = "global::" + namespaceName + "." + callTypeName;
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();

            AppendRpcServiceCall(builder, callTypeName);

            builder.Append("internal sealed class ").Append(proxyName).Append(" : ").Append(contractDisplay).AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    private readonly global::Lakona.Game.Server.Hotfix.IHotfixRuntimeAccessor _hotfixRuntime;");
            builder.AppendLine("    private readonly global::Lakona.Game.Server.Actors.IActorRuntime _actors;");
            builder.AppendLine("    private readonly global::Lakona.Game.Server.ILakonaGameServer _gameServer;");
            builder.AppendLine("    private readonly string _connectionId;");
            builder.AppendLine();
            builder.Append("    public ").Append(proxyName).AppendLine("(");
            builder.AppendLine("        global::Lakona.Game.Server.Hotfix.IHotfixRuntimeAccessor hotfixRuntime,");
            builder.AppendLine("        global::Lakona.Game.Server.Actors.IActorRuntime actors,");
            builder.AppendLine("        global::Lakona.Game.Server.ILakonaGameServer gameServer,");
            builder.AppendLine("        string connectionId)");
            builder.AppendLine("    {");
            builder.AppendLine("        _hotfixRuntime = hotfixRuntime;");
            builder.AppendLine("        _actors = actors;");
            builder.AppendLine("        _gameServer = gameServer;");
            builder.AppendLine("        _connectionId = connectionId;");
            builder.AppendLine("    }");

            foreach (var method in service.Contract.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(method => method.MethodKind == MethodKind.Ordinary))
            {
                AppendRpcProxyMethod(builder, contractDisplay, method, callTypeDisplay);
            }

            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendRpcServiceCall(StringBuilder builder, string callTypeName)
        {
            const string innerCallType = "global::Lakona.Game.Server.Hotfix.HotfixServiceCall<TRequest>";

            builder.Append("public readonly struct ").Append(callTypeName)
                .AppendLine("<TRequest> : global::Lakona.Game.Server.Hotfix.IHotfixServiceCall<TRequest>");
            builder.AppendLine("{");
            builder.Append("    private readonly ").Append(innerCallType).AppendLine(" _inner;");
            builder.AppendLine();
            builder.Append("    public ").Append(callTypeName).AppendLine("(");
            builder.AppendLine("        TRequest request,");
            builder.AppendLine("        string connectionId,");
            builder.AppendLine("        global::Lakona.Game.Server.Sessions.GameSessionKey? currentSession,");
            builder.AppendLine("        global::Lakona.Game.Server.Sessions.GameSessionItems currentSessionItems,");
            builder.AppendLine("        global::System.IServiceProvider services,");
            builder.AppendLine("        global::Lakona.Game.Server.Actors.IActorRuntime actors,");
            builder.AppendLine("        global::Lakona.Game.Server.ILakonaGameServer gameServer)");
            builder.AppendLine("    {");
            builder.Append("        _inner = new ").Append(innerCallType).AppendLine("(");
            builder.AppendLine("            request,");
            builder.AppendLine("            connectionId,");
            builder.AppendLine("            currentSession,");
            builder.AppendLine("            currentSessionItems,");
            builder.AppendLine("            services,");
            builder.AppendLine("            actors,");
            builder.AppendLine("            gameServer);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public TRequest Request => _inner.Request;");
            builder.AppendLine();
            builder.AppendLine("    public string ConnectionId => _inner.ConnectionId;");
            builder.AppendLine();
            builder.AppendLine("    public global::Lakona.Game.Server.Sessions.GameSessionKey? CurrentSession => _inner.CurrentSession;");
            builder.AppendLine();
            builder.AppendLine("    public global::Lakona.Game.Server.Sessions.GameSessionItems CurrentSessionItems => _inner.CurrentSessionItems;");
            builder.AppendLine();
            builder.AppendLine("    public global::System.IServiceProvider Services => _inner.Services;");
            builder.AppendLine();
            builder.AppendLine("    public global::Lakona.Game.Server.Actors.IActorRuntime Actors => _inner.Actors;");
            builder.AppendLine();
            builder.AppendLine("    public global::Lakona.Game.Server.ILakonaGameServer GameServer => _inner.GameServer;");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        private static void AppendRpcProxyMethod(
            StringBuilder builder,
            string contractDisplay,
            IMethodSymbol method,
            string callTypeDisplay)
        {
            var rpcMethod = method.GetAttributes()
                .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == RpcMethodAttributeName);
            if (rpcMethod == null || method.Parameters.Length != 1)
            {
                return;
            }

            var requestDisplay = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var returnDisplay = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodId = rpcMethod.ConstructorArguments.Length > 0
                ? rpcMethod.ConstructorArguments[0].Value?.ToString() ?? "0"
                : "0";
            var returnsResult = method.ReturnType is INamedTypeSymbol namedReturn &&
                namedReturn.IsGenericType &&
                namedReturn.Name == "ValueTask" &&
                namedReturn.TypeArguments.Length == 1;
            var resultDisplay = returnsResult && method.ReturnType is INamedTypeSymbol valueTask
                ? valueTask.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : null;
            var callType = callTypeDisplay + "<" + requestDisplay + ">";

            builder.AppendLine();
            builder.Append("    public async ").Append(returnDisplay).Append(' ').Append(method.Name).Append('(')
                .Append(requestDisplay).Append(' ').Append(method.Parameters[0].Name).AppendLine(")");
            builder.AppendLine("    {");
            builder.AppendLine("        using var lease = _hotfixRuntime.AcquireCurrent();");
            builder.AppendLine("        var snapshot = lease.Snapshot;");
            builder.AppendLine("        var sessions = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions");
            builder.AppendLine("            .GetRequiredService<global::Lakona.Game.Server.Sessions.IGameSessionRegistry>(snapshot.Services);");
            builder.AppendLine("        var currentSession = await sessions");
            builder.AppendLine("            .GetCurrentSessionAsync(_connectionId, global::System.Threading.CancellationToken.None)");
            builder.AppendLine("            .ConfigureAwait(false);");
            builder.AppendLine("        var currentSessionItems = currentSession is { } sessionKey");
            builder.AppendLine("            ? await sessions.GetSessionItemsAsync(sessionKey, global::System.Threading.CancellationToken.None).ConfigureAwait(false)");
            builder.AppendLine("            : global::Lakona.Game.Server.Sessions.GameSessionItems.Empty;");
            builder.Append("        ");
            if (returnsResult)
            {
                builder.Append("return ");
            }

            builder.Append("await snapshot.Invoker.InvokeAsync<").Append(contractDisplay).Append(", ").Append(callType);
            if (returnsResult)
            {
                builder.Append(", ").Append(resultDisplay);
            }

            builder.AppendLine(">(");
            builder.Append("            ").Append(methodId).AppendLine(",");
            builder.Append("            new ").Append(callType).AppendLine("(");
            builder.Append("                ").Append(method.Parameters[0].Name).AppendLine(",");
            builder.AppendLine("                _connectionId,");
            builder.AppendLine("                currentSession,");
            builder.AppendLine("                currentSessionItems,");
            builder.AppendLine("                snapshot.Services,");
            builder.AppendLine("                _actors,");
            builder.AppendLine("                _gameServer))");
            builder.AppendLine("            .ConfigureAwait(false);");
            builder.AppendLine("    }");
        }

        private static string CreateRpcServiceHintName(INamedTypeSymbol symbol)
        {
            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", string.Empty)
                .Replace('.', '_')
                .Replace('<', '_')
                .Replace('>', '_')
                .Replace(',', '_')
                .Replace(' ', '_') + ".HotfixRpcService.g.cs";
        }

        private static string GetGeneratedProxyTypeDisplay(HotfixRpcServiceInfo service)
        {
            var proxyName = GetServiceTypeName(service.Contract.Name) + "Proxy";
            if (string.IsNullOrEmpty(service.GeneratedProxyNamespace))
            {
                return proxyName;
            }

            return "global::" + service.GeneratedProxyNamespace + "." + proxyName;
        }

        private static INamedTypeSymbol? GetNamedTypeArgument(AttributeData? attribute, string name)
        {
            if (attribute == null)
            {
                return null;
            }

            foreach (var namedArgument in attribute.NamedArguments)
            {
                if (namedArgument.Key == name && namedArgument.Value.Value is INamedTypeSymbol namedType)
                {
                    return namedType;
                }
            }

            return null;
        }

        private static string? GetNamedStringArgument(AttributeData? attribute, string name)
        {
            if (attribute == null)
            {
                return null;
            }

            foreach (var namedArgument in attribute.NamedArguments)
            {
                if (namedArgument.Key == name && namedArgument.Value.Value is string value)
                {
                    return value;
                }
            }

            return null;
        }

        private static string GetEndpointServiceName(HotfixRpcServiceInfo service)
        {
            var rpcServiceAttribute = service.Contract.GetAttributes()
                .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == RpcServiceAttributeName);
            var apiName = GetNamedStringArgument(rpcServiceAttribute, "ApiName");
            var sourceName = string.IsNullOrWhiteSpace(apiName)
                ? GetEndpointServiceBaseName(service.Contract.Name)
                : apiName!;

            return ToKebabCase(sourceName);
        }

        private static string GetServiceTypeName(string interfaceName)
        {
            return interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
                ? interfaceName.Substring(1)
                : interfaceName;
        }

        private static string GetEndpointServiceBaseName(string interfaceName)
        {
            var name = GetServiceTypeName(interfaceName);
            const string suffix = "Service";
            return name.EndsWith(suffix, System.StringComparison.Ordinal) && name.Length > suffix.Length
                ? name.Substring(0, name.Length - suffix.Length)
                : name;
        }

        private static string ToKebabCase(string value)
        {
            var builder = new StringBuilder();
            for (var index = 0; index < value.Length; index++)
            {
                var character = value[index];
                if (IsAsciiLetterOrDigit(character))
                {
                    if (IsAsciiUpper(character) && builder.Length > 0)
                    {
                        var previous = value[index - 1];
                        var next = index + 1 < value.Length ? value[index + 1] : '\0';
                        if (IsAsciiLower(previous) ||
                            IsAsciiDigit(previous) ||
                            (IsAsciiUpper(previous) && IsAsciiLower(next)))
                        {
                            AppendDash(builder);
                        }
                    }

                    builder.Append(ToAsciiLower(character));
                    continue;
                }

                AppendDash(builder);
            }

            while (builder.Length > 0 && builder[builder.Length - 1] == '-')
            {
                builder.Length--;
            }

            if (builder.Length == 0)
            {
                return "service";
            }

            if (IsAsciiDigit(builder[0]))
            {
                builder.Insert(0, "service-");
            }

            return builder.ToString();
        }

        private static void AppendDash(StringBuilder builder)
        {
            if (builder.Length > 0 && builder[builder.Length - 1] != '-')
            {
                builder.Append('-');
            }
        }

        private static bool IsAsciiLetterOrDigit(char value)
        {
            return IsAsciiLower(value) || IsAsciiUpper(value) || IsAsciiDigit(value);
        }

        private static bool IsAsciiLower(char value)
        {
            return value >= 'a' && value <= 'z';
        }

        private static bool IsAsciiUpper(char value)
        {
            return value >= 'A' && value <= 'Z';
        }

        private static bool IsAsciiDigit(char value)
        {
            return value >= '0' && value <= '9';
        }

        private static char ToAsciiLower(char value)
        {
            return IsAsciiUpper(value) ? (char)(value + ('a' - 'A')) : value;
        }

        private static string GetBinderTypeName(string interfaceName)
        {
            return GetServiceTypeName(interfaceName) + "Binder";
        }

        private static string GetNotificationProxyTypeName(string notificationContractInterfaceName)
        {
            return GetServiceTypeName(notificationContractInterfaceName) + "Proxy";
        }

        private sealed class HotfixRpcServiceInfo
        {
            public HotfixRpcServiceInfo(
                INamedTypeSymbol contract,
                string generatedProxyNamespace,
                string generatedServerNamespace)
            {
                Contract = contract;
                GeneratedProxyNamespace = generatedProxyNamespace;
                GeneratedServerNamespace = generatedServerNamespace;
            }

            public INamedTypeSymbol Contract { get; }

            public string GeneratedProxyNamespace { get; }

            public string GeneratedServerNamespace { get; }
        }
    }
}
