using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Lakona.Game.Server.Hotfix.Generators
{
    public sealed partial class HotfixGenerator
    {
        private const string HotfixComponentAttributeName =
            "Lakona.Game.Server.Hotfix.Abstractions.HotfixComponentAttribute";

        private static IEnumerable<INamedTypeSymbol> DiscoverHotfixComponents(
            Compilation compilation,
            CancellationToken cancellationToken)
        {
            foreach (var type in EnumerateTypes(compilation.Assembly.GlobalNamespace))
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (HasAttribute(type, HotfixComponentAttributeName))
                {
                    yield return type;
                }
            }
        }

        private static void GenerateComponentRegistration(
            SourceProductionContext context,
            INamedTypeSymbol[] components)
        {
            if (components.Length == 0)
            {
                return;
            }

            var supported = new List<INamedTypeSymbol>();
            foreach (var component in components)
            {
                var declaration = component.DeclaringSyntaxReferences
                    .Select(static reference => reference.GetSyntax())
                    .OfType<TypeDeclarationSyntax>()
                    .FirstOrDefault();
                if (component.TypeKind != TypeKind.Class ||
                    component.IsStatic ||
                    component.IsAbstract ||
                    !component.IsSealed ||
                    component.TypeParameters.Length != 0 ||
                    component.ContainingType is not null ||
                    declaration is null ||
                    HasFileModifier(declaration))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        HotfixGeneratorDiagnostics.HotfixComponentModuleShape,
                        component.Locations.FirstOrDefault(static location => location.IsInSource),
                        component.ToDisplayString()));
                    continue;
                }

                supported.Add(component);
            }

            if (supported.Count == 0)
            {
                return;
            }

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("namespace Lakona.Game.Server.Hotfix.Generated;");
            builder.AppendLine();
            builder.AppendLine("internal sealed class GeneratedHotfixComponentRegistration :");
            builder.AppendLine("    global::Lakona.Game.Server.Hotfix.IHotfixGeneratedServiceRegistration");
            builder.AppendLine("{");
            builder.AppendLine("    public void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            builder.AppendLine("    {");
            foreach (var component in supported.OrderBy(
                static item => item.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                System.StringComparer.Ordinal))
            {
                builder.Append("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<")
                    .Append(component.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .AppendLine(">(services);");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            context.AddSource(
                "GeneratedHotfixComponents.g.cs",
                SourceText.From(builder.ToString(), Encoding.UTF8));
        }
    }
}
