using System.Text;

namespace Lakona.Rpc.Analyzers;

public sealed partial class LakonaRpcSourceGenerator
{
    private sealed class SourceWriter
    {
        private readonly StringBuilder _builder = new();
        private int _indent;

        public void Header()
        {
            Line("// <auto-generated/>");
            Line("// This file was auto-generated by Lakona.Rpc.Analyzers. Do not edit.");
            Line("#pragma warning disable");
            Line("#nullable enable");
            Line();
        }

        public void Line(string text)
        {
            for (var i = 0; i < _indent; i++)
                _builder.Append("    ");
            _builder.Append(text).Append('\n');
        }

        public void Line() => _builder.Append('\n');

        public void OpenBlock(string header)
        {
            Line(header);
            Line("{");
            _indent++;
        }

        public void CloseBlock(string suffix = "")
        {
            _indent--;
            Line("}" + suffix);
        }

        public void Indent()
        {
            _indent++;
        }

        public void Unindent()
        {
            _indent--;
        }

        public override string ToString() => _builder.ToString();
    }
}
