<Project>
  <ItemGroup>
    <CompilerVisibleProperty Include="LakonaRpcGenerateClient" />
    <CompilerVisibleProperty Include="LakonaRpcGenerateServer" />
    <CompilerVisibleProperty Include="LakonaRpcGeneratedNamespace" />
    <CompilerVisibleProperty Include="LakonaRpcServerGeneratedNamespace" />
    <CompilerVisibleProperty Include="LakonaGameGenerateClient" />
    <CompilerVisibleProperty Include="LakonaGameClientRuntime" />
    <CompilerVisibleProperty Include="LakonaGameClientPlatform" />
    <CompilerVisibleProperty Include="LakonaGameClientGameVersion" />
  </ItemGroup>
</Project>
