<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\BuildTag.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Server.App</RootNamespace>
    <AssemblyName>Server.App</AssemblyName>
    <BuildInParallel>false</BuildInParallel>
    <LakonaProjectRole>ServerApp</LakonaProjectRole>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="LakonaProjectRole" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="MemoryPack.Generator" Version="1.21.4" PrivateAssets="all" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" TargetFramework="net10.0">
      <SetTargetFramework>TargetFramework=net10.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Server\Lakona.Game.Server.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Server.Hotfix.Generators\Lakona.Game.Server.Hotfix.Generators.csproj" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Rpc.Serializer.MemoryPack\Lakona.Rpc.Serializer.MemoryPack.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Rpc.Transport.WebSocket\Lakona.Rpc.Transport.WebSocket.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Rpc.Analyzers\Lakona.Rpc.Analyzers.csproj"
                      ReferenceOutputAssembly="false"
                      OutputItemType="Analyzer"
                      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>LakonaBuildTag</_Parameter1>
      <_Parameter2>$(LakonaBuildTag)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Server.Hotfix</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
