<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="BuildTag.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Server.App</RootNamespace>
    <AssemblyName>Server.App</AssemblyName>
    <BuildInParallel>false</BuildInParallel>
    <RestoreBuildInParallel>false</RestoreBuildInParallel>
    <LakonaRpcGenerateServer>true</LakonaRpcGenerateServer>
    <LakonaRpcServerGeneratedNamespace>Server.App.Generated</LakonaRpcServerGeneratedNamespace>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="LakonaRpcGenerateServer" />
    <CompilerVisibleProperty Include="LakonaRpcServerGeneratedNamespace" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" TargetFramework="net10.0">
      <SetTargetFramework>TargetFramework=net10.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Server\Lakona.Game.Server.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Server.Hotfix\Lakona.Game.Server.Hotfix.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Server.Hotfix.Abstractions\Lakona.Game.Server.Hotfix.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Server.Hotfix.Generators\Lakona.Game.Server.Hotfix.Generators.csproj" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Server.Generators\Lakona.Game.Server.Generators.csproj" PrivateAssets="all" OutputItemType="Analyzer" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Rpc.Server\Lakona.Rpc.Server.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Cluster\Lakona.Game.Cluster.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Game.Cluster.Rpc\Lakona.Game.Cluster.Rpc.csproj" />
    <ProjectReference Include="..\..\..\..\src\Lakona.Rpc.Analyzers\Lakona.Rpc.Analyzers.csproj"
                      ReferenceOutputAssembly="false"
                      OutputItemType="Analyzer"
                      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>LakonaHotfixBuildTag</_Parameter1>
      <_Parameter2>$(LakonaHotfixBuildTag)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Server.Hotfix</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
