using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Lakona.Game.Server.Generators
{
    public sealed partial class TypedActorGenerator
    {
        private static void GenerateActorAccess(
            SourceProductionContext context,
            ImmutableArray<ActorInfo?> actorCandidates)
        {
            var actors = actorCandidates
                .Where(static actor => actor is not null)
                .Select(static actor => actor!)
                .OrderBy(static actor => actor.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .ToArray();
            if (actors.Length == 0)
            {
                return;
            }

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine();
            builder.AppendLine("namespace Lakona.Game.Server.Generated");
            builder.AppendLine("{");
            AppendActorDelegates(builder);
            builder.AppendLine();
            AppendActorAccessRoot(builder, actors);
            builder.AppendLine();
            AppendLocalActorSelector(builder);
            builder.AppendLine();
            AppendActorRouteSelector(builder);
            builder.AppendLine();
            AppendActorPlacementSelector(builder);
            builder.AppendLine();
            AppendGeneratedActorMetadata(builder, actors);
            builder.AppendLine();
            AppendActorAccessRegistration(builder, actors);
            builder.AppendLine("}");
            context.AddSource("GeneratedActorAccess.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private static void AppendActorDelegates(StringBuilder builder)
        {
            builder.AppendLine("public delegate global::System.Threading.Tasks.ValueTask<TResult> ActorCall<in TActor, in TRequest, TResult>(");
            builder.AppendLine("    TActor self,");
            builder.AppendLine("    TRequest request,");
            builder.AppendLine("    global::System.Threading.CancellationToken cancellationToken);");
            builder.AppendLine();
            builder.AppendLine("public delegate global::System.Threading.Tasks.ValueTask<TResult> ActorCallNoCancellation<in TActor, in TRequest, TResult>(");
            builder.AppendLine("    TActor self,");
            builder.AppendLine("    TRequest request);");
            builder.AppendLine();
            builder.AppendLine("public delegate global::System.Threading.Tasks.ValueTask ActorPost<in TActor, in TRequest>(");
            builder.AppendLine("    TActor self,");
            builder.AppendLine("    TRequest request,");
            builder.AppendLine("    global::System.Threading.CancellationToken cancellationToken);");
            builder.AppendLine();
            builder.AppendLine("public delegate global::System.Threading.Tasks.ValueTask ActorPostNoCancellation<in TActor, in TRequest>(");
            builder.AppendLine("    TActor self,");
            builder.AppendLine("    TRequest request);");
        }

        private static void AppendActorAccessRoot(StringBuilder builder, ActorInfo[] actors)
        {
            builder.AppendLine("public sealed class ActorAccess");
            builder.AppendLine("{");
            builder.AppendLine("    private readonly global::Lakona.Game.Server.Actors.IActorRuntime _runtime;");
            builder.AppendLine("    private readonly global::System.IServiceProvider _services;");
            builder.AppendLine("    private readonly global::Lakona.Game.Server.Actors.RemoteActorOptions _options;");
            builder.AppendLine("    private readonly global::Lakona.Game.Server.Actors.IActorDirectory _directory;");
            builder.AppendLine("    private readonly global::Lakona.Game.Server.Actors.IActorDirectoryCache _directoryCache;");
            builder.AppendLine("    private readonly global::Lakona.Game.Server.Actors.IActorPlacementService _placement;");
            builder.AppendLine();
            builder.AppendLine("    public ActorAccess(");
            builder.AppendLine("        global::Lakona.Game.Server.Actors.IActorRuntime runtime,");
            builder.AppendLine("        global::System.IServiceProvider services,");
            builder.AppendLine("        global::Lakona.Game.Server.Actors.RemoteActorOptions options,");
            builder.AppendLine("        global::Lakona.Game.Server.Actors.IActorDirectory directory,");
            builder.AppendLine("        global::Lakona.Game.Server.Actors.IActorDirectoryCache directoryCache,");
            builder.AppendLine("        global::Lakona.Game.Server.Actors.IActorPlacementService placement)");
            builder.AppendLine("    {");
            builder.AppendLine("        _runtime = runtime;");
            builder.AppendLine("        _services = services;");
            builder.AppendLine("        _options = options;");
            builder.AppendLine("        _directory = directory;");
            builder.AppendLine("        _directoryCache = directoryCache;");
            builder.AppendLine("        _placement = placement;");
            builder.AppendLine("    }");

            foreach (var actor in DistinctKeyActors(actors))
            {
                var keyType = actor.KeyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var accessibility = ResolveKeyOverloadAccessibility(actors, actor.KeyType);
                var keyValue = CreateKeyValueExpression(actor.KeyType, "id");
                builder.AppendLine();
                builder.Append("    ").Append(accessibility).Append(" LocalActor<TActor> Local<TActor>(").Append(keyType).AppendLine(" id)");
                builder.Append("        where TActor : global::Lakona.Game.Server.Actors.Actor<").Append(keyType).AppendLine(">");
                builder.AppendLine("    {");
                builder.Append("        var actorId = global::Lakona.Game.Server.Actors.ActorId.From(GeneratedActorMetadata<TActor>.ActorName + \"/\" + ").Append(keyValue).AppendLine(");");
                builder.AppendLine("        return new LocalActor<TActor>(_runtime, actorId);");
                builder.AppendLine("    }");
                if (!actors.Any(candidate =>
                    SymbolEqualityComparer.Default.Equals(candidate.KeyType, actor.KeyType) &&
                    !candidate.IsLocalOnly))
                {
                    continue;
                }

                builder.AppendLine();
                builder.Append("    ").Append(accessibility).Append(" ActorRoute<TActor> Route<TActor>(").Append(keyType).AppendLine(" id)");
                builder.Append("        where TActor : global::Lakona.Game.Server.Actors.Actor<").Append(keyType).AppendLine(">");
                builder.AppendLine("    {");
                builder.Append("        var actorId = global::Lakona.Game.Server.Actors.ActorId.From(GeneratedActorMetadata<TActor>.ActorName + \"/\" + ").Append(keyValue).AppendLine(");");
                builder.AppendLine("        return new ActorRoute<TActor>(this, actorId);");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.Append("    ").Append(accessibility).Append(" ActorPlacement<TActor, ").Append(keyType).Append("> Place<TActor>(").Append(keyType).AppendLine(" id)");
                builder.Append("        where TActor : global::Lakona.Game.Server.Actors.Actor<").Append(keyType).AppendLine(">");
                builder.AppendLine("    {");
                builder.Append("        return new ActorPlacement<TActor, ").Append(keyType).AppendLine(">(_placement, id);");
                builder.AppendLine("    }");
            }

            builder.AppendLine();
            builder.AppendLine("    internal global::Lakona.Game.Server.Actors.IActorRuntime Runtime => _runtime;");
            builder.AppendLine("    internal global::Lakona.Game.Server.Actors.IRemoteActorInvoker Remote => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Lakona.Game.Server.Actors.IRemoteActorInvoker>(_services);");
            builder.AppendLine("    internal global::Lakona.Game.Server.Actors.IRemoteActorSerializer Serializer => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Lakona.Game.Server.Actors.IRemoteActorSerializer>(_services);");
            builder.AppendLine("    internal global::Lakona.Game.Server.Actors.RemoteActorOptions Options => _options;");
            builder.AppendLine("    internal global::Lakona.Game.Server.Actors.IActorDirectory Directory => _directory;");
            builder.AppendLine("    internal global::Lakona.Game.Server.Actors.IActorDirectoryCache DirectoryCache => _directoryCache;");
            builder.AppendLine("}");
        }

        private static IEnumerable<ActorInfo> DistinctKeyActors(ActorInfo[] actors)
        {
            var keys = new List<ITypeSymbol>();
            foreach (var actor in actors)
            {
                if (keys.Any(key => SymbolEqualityComparer.Default.Equals(key, actor.KeyType)))
                {
                    continue;
                }

                keys.Add(actor.KeyType);
                yield return actor;
            }
        }

        private static string ResolveKeyOverloadAccessibility(ActorInfo[] actors, ITypeSymbol keyType)
        {
            return actors.Any(actor =>
                SymbolEqualityComparer.Default.Equals(actor.KeyType, keyType) &&
                IsPubliclyAccessible(actor.Symbol) &&
                IsPubliclyAccessible(keyType))
                ? "public"
                : "internal";
        }

        private static bool IsPubliclyAccessible(ISymbol symbol)
        {
            for (var current = symbol; current is not null; current = current.ContainingType)
            {
                if (current.DeclaredAccessibility != Accessibility.Public &&
                    current.DeclaredAccessibility != Accessibility.NotApplicable)
                {
                    return false;
                }
            }

            return true;
        }

        private static void AppendActorCallApi(StringBuilder builder)
        {
            builder.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResult> CallAsync<TRequest, TResult>(");
            builder.AppendLine("        ActorCall<TActor, TRequest, TResult> method,");
            builder.AppendLine("        TRequest request,");
            builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        var methodName = GeneratedActorMetadata<TActor>.ResolveActorMethod(method, typeof(TRequest), typeof(TResult));");
            builder.AppendLine("        return CallCoreAsync((actor, value, ct) => method(actor, value, ct), methodName, request, cancellationToken);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResult> CallAsync<TRequest, TResult>(");
            builder.AppendLine("        ActorCallNoCancellation<TActor, TRequest, TResult> method,");
            builder.AppendLine("        TRequest request,");
            builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        var methodName = GeneratedActorMetadata<TActor>.ResolveActorMethod(method, typeof(TRequest), typeof(TResult));");
            builder.AppendLine("        return CallCoreAsync((actor, value, _) => method(actor, value), methodName, request, cancellationToken);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public global::System.Threading.Tasks.ValueTask CallAsync<TRequest>(");
            builder.AppendLine("        ActorPost<TActor, TRequest> method,");
            builder.AppendLine("        TRequest request,");
            builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        var methodName = GeneratedActorMetadata<TActor>.ResolveActorMethod(method, typeof(TRequest), resultType: null);");
            builder.AppendLine("        return CallCoreAsync((actor, value, ct) => method(actor, value, ct), methodName, request, cancellationToken);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public global::System.Threading.Tasks.ValueTask CallAsync<TRequest>(");
            builder.AppendLine("        ActorPostNoCancellation<TActor, TRequest> method,");
            builder.AppendLine("        TRequest request,");
            builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        var methodName = GeneratedActorMetadata<TActor>.ResolveActorMethod(method, typeof(TRequest), resultType: null);");
            builder.AppendLine("        return CallCoreAsync((actor, value, _) => method(actor, value), methodName, request, cancellationToken);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public global::System.Threading.Tasks.ValueTask PostAsync<TRequest>(");
            builder.AppendLine("        ActorPost<TActor, TRequest> method,");
            builder.AppendLine("        TRequest request,");
            builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        var methodName = GeneratedActorMetadata<TActor>.ResolveActorMethod(method, typeof(TRequest), resultType: null);");
            builder.AppendLine("        return PostCoreAsync((actor, value, ct) => method(actor, value, ct), methodName, request, cancellationToken);");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public global::System.Threading.Tasks.ValueTask PostAsync<TRequest>(");
            builder.AppendLine("        ActorPostNoCancellation<TActor, TRequest> method,");
            builder.AppendLine("        TRequest request,");
            builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        var methodName = GeneratedActorMetadata<TActor>.ResolveActorMethod(method, typeof(TRequest), resultType: null);");
            builder.AppendLine("        return PostCoreAsync((actor, value, _) => method(actor, value), methodName, request, cancellationToken);");
            builder.AppendLine("    }");
        }

        private static void AppendGeneratedActorMetadata(StringBuilder builder, ActorInfo[] actors)
        {
            builder.AppendLine("internal static class GeneratedActorMetadata<TActor>");
            builder.AppendLine("    where TActor : global::Lakona.Game.Server.Actors.Actor");
            builder.AppendLine("{");
            builder.AppendLine("    public static readonly string ActorName = ResolveActorName();");
            builder.AppendLine();
            builder.AppendLine("    public static string ResolveActorMethod(global::System.Delegate method, global::System.Type requestType, global::System.Type resultType)");
            builder.AppendLine("    {");
            builder.AppendLine("        var methodInfo = method.Method;");
            builder.AppendLine("        var declaringTypeName = methodInfo.DeclaringType?.FullName;");
            builder.AppendLine("        var methodName = methodInfo.Name;");
            builder.AppendLine();
            foreach (var actor in actors)
            {
                var actorType = actor.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var runtimeTypeName = GetRuntimeTypeFullName(actor.Symbol);
                builder.Append("        if (typeof(TActor) == typeof(").Append(actorType).AppendLine("))");
                builder.AppendLine("        {");
                foreach (var method in actor.Methods)
                {
                    var requestType = method.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var resultType = method.ResultType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    builder.Append("            if (declaringTypeName == \"").Append(EscapeStringLiteral(runtimeTypeName)).AppendLine("\"");
                    builder.Append("                && methodName == \"").Append(EscapeStringLiteral(method.Name)).AppendLine("\"");
                    builder.Append("                && requestType == typeof(").Append(requestType).AppendLine(")");
                    if (resultType is null)
                    {
                        builder.AppendLine("                && resultType == null)");
                    }
                    else
                    {
                        builder.Append("                && resultType == typeof(").Append(resultType).AppendLine("))");
                    }

                    builder.AppendLine("            {");
                    builder.Append("                return \"").Append(EscapeStringLiteral(method.ActorMethodName)).AppendLine("\";");
                    builder.AppendLine("            }");
                    builder.AppendLine();
                }

                builder.Append("            throw new global::System.ArgumentException(\"The supplied method is not a generated actor method for ")
                    .Append(EscapeStringLiteral(actor.Symbol.Name))
                    .AppendLine(".\", nameof(method));");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        throw new global::System.ArgumentException(\"The actor type is not part of the generated actor API.\", nameof(TActor));");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    private static string ResolveActorName()");
            builder.AppendLine("    {");
            foreach (var actor in actors)
            {
                var actorType = actor.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.Append("        if (typeof(TActor) == typeof(").Append(actorType).AppendLine("))");
                builder.AppendLine("        {");
                builder.Append("            return \"").Append(EscapeStringLiteral(actor.ActorName)).AppendLine("\";");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        throw new global::System.ArgumentException(\"The actor type is not part of the generated actor API.\", nameof(TActor));");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        private static void AppendActorAccessRegistration(StringBuilder builder, ActorInfo[] actors)
        {
            builder.AppendLine("public static class GeneratedActorServiceCollectionExtensions");
            builder.AppendLine("{");
            builder.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedActorAccess(");
            builder.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            builder.AppendLine("    {");
            builder.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<ActorAccess>(services);");
            foreach (var actor in actors.Where(static actor => !actor.IsLocalOnly))
            {
                var actorNamespace = actor.Symbol.ContainingNamespace.IsGlobalNamespace
                    ? string.Empty
                    : actor.Symbol.ContainingNamespace.ToDisplayString() + ".";
                builder.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(");
                builder.AppendLine("            services,");
                builder.AppendLine("            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<");
                builder.AppendLine("                global::Lakona.Game.Cluster.IClusterMessageHandler,");
                builder.Append("                global::").Append(actorNamespace).Append(actor.Symbol.Name).AppendLine("ClusterHandler>());");
            }

            builder.AppendLine("        return services;");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }
    }
}
