namespace Lakona.ProjectSystem.Generation.Domain;

internal sealed class PackageCatalog
{
    public string MicrosoftExtensionsLoggingConsole => "8.0.0";
    public string MicrosoftExtensionsLoggingConsoleServer => "10.0.0";
    public string MicrosoftExtensionsLogging => "8.0.0";
    public string MicrosoftExtensionsLoggingAbstractions => "8.0.0";
    public string MicrosoftExtensionsLoggingConfiguration => "8.0.0";
    public string MicrosoftExtensionsDependencyInjection => "8.0.0";
    public string MicrosoftExtensionsDependencyInjectionAbstractions => "8.0.0";
    public string MicrosoftExtensionsConfiguration => "8.0.0";
    public string MicrosoftExtensionsConfigurationAbstractions => "8.0.0";
    public string MicrosoftExtensionsConfigurationBinder => "8.0.0";
    public string MicrosoftExtensionsOptions => "8.0.0";
    public string MicrosoftExtensionsOptionsConfigurationExtensions => "8.0.0";
    public string MicrosoftExtensionsPrimitives => "8.0.0";
    public string SystemDiagnosticsDiagnosticSource => "8.0.0";
    public string SystemComponentModelAnnotations => "5.0.0";
    public string MemoryPack => "1.21.4";
    public string MemoryPackCore => "1.21.4";
    public string LakonaGameAbstractions => global::GeneratedProjectPackageVersions.LakonaGameAbstractions;
    public string LakonaGameClient => global::GeneratedProjectPackageVersions.LakonaGameClient;
    public string LakonaGameLoadTesting => global::GeneratedProjectPackageVersions.LakonaGameLoadTesting;
    public string LakonaGameServer => global::GeneratedProjectPackageVersions.LakonaGameServer;
    public string LakonaGameClusteringPostgres => global::GeneratedProjectPackageVersions.LakonaGameClusteringPostgres;
    public string LakonaGameClusteringRedis => global::GeneratedProjectPackageVersions.LakonaGameClusteringRedis;
    public string LakonaGameClusteringMySql => global::GeneratedProjectPackageVersions.LakonaGameClusteringMySql;
    public string LakonaRpcCore => global::GeneratedProjectPackageVersions.LakonaRpcCore;
    public string LakonaRpcClient => global::GeneratedProjectPackageVersions.LakonaRpcClient;
    public string LakonaRpcTransportTcp => global::GeneratedProjectPackageVersions.LakonaRpcTransportTcp;
    public string LakonaRpcTransportWebSocket => global::GeneratedProjectPackageVersions.LakonaRpcTransportWebSocket;
    public string LakonaRpcTransportKcp => global::GeneratedProjectPackageVersions.LakonaRpcTransportKcp;
    public string LakonaRpcSerializerJson => global::GeneratedProjectPackageVersions.LakonaRpcSerializerJson;
    public string LakonaRpcSerializerMemoryPack => global::GeneratedProjectPackageVersions.LakonaRpcSerializerMemoryPack;
    public string Kcp => "2.7.0";
    public string MicrosoftBclAsyncInterfaces => "8.0.0";
    public string SystemBuffers => "4.6.1";
    public string SystemCollectionsImmutable => "10.0.6";
    public string MicrosoftCodeAnalysisCommon => "5.3.0";
    public string MicrosoftCodeAnalysisCSharp => "5.3.0";
    public string SystemReflectionMetadata => "10.0.7";
    public string SystemTextEncodingCodePages => "10.0.7";
    public string SystemThreadingTasksExtensionsForRoslyn => "4.5.4";
    public string SystemMemoryForRoslyn => "4.5.4";
    public string SystemIoPipelinesForJson => "10.0.6";
    public string SystemMemoryForJson => "4.6.3";
    public string SystemMemoryForKcp => "4.5.4";
    public string SystemThreadingChannels => "8.0.0";
    public string SystemTextEncodingsWeb => "8.0.0";
    public string SystemTextJson => "8.0.6";
    public string SystemThreadingTasksExtensionsForJson => "4.6.3";
    public string SystemThreadingTasksExtensionsForKcp => "4.5.4";
    public string SystemRuntimeCompilerServicesUnsafe => "6.1.2";
    public string SystemIoPipelines => "10.0.6";
}
