**

!NuGet.config
!Directory.Build.props

!src/
!src/ULinkGame.Server/
!src/ULinkGame.Server/**

!samples/
!samples/Game.Unity.Agar/
!samples/Game.Unity.Agar/Shared/
!samples/Game.Unity.Agar/Shared/**
!samples/Game.Unity.Agar/Server/
!samples/Game.Unity.Agar/Server/**

**/.idea/
**/.vs/
**/bin/
**/obj/
**/Library/
**/Logs/
**/Temp/
**/UserSettings/
