<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <UseAppHost>false</UseAppHost>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <LakonaRpcGenerateServer>true</LakonaRpcGenerateServer>
    <LakonaRpcServerGeneratedNamespace>FrameworkBenchmark.Lakona.Server.Generated</LakonaRpcServerGeneratedNamespace>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="LakonaRpcGenerateServer" />
    <CompilerVisibleProperty Include="LakonaRpcServerGeneratedNamespace" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FrameworkBenchmark.Lakona.Contracts\FrameworkBenchmark.Lakona.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Lakona.Rpc.Analyzers\Lakona.Rpc.Analyzers.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" PrivateAssets="all" />
    <ProjectReference Include="..\..\..\..\..\src\Lakona.Rpc.Server\Lakona.Rpc.Server.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Lakona.Rpc.Serializer.MemoryPack\Lakona.Rpc.Serializer.MemoryPack.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\Lakona.Rpc.Transport.WebSocket\Lakona.Rpc.Transport.WebSocket.csproj" />
  </ItemGroup>
</Project>
